index:
  path: /
  controller: App\Controller\MainController::index
  methods: GET

transaction-create:
  path: /transaction
  controller: App\Controller\TransactionController::create
  methods: POST

dashboard:
  path: /dashboard
  controller: App\Controller\DashboardController::index
  methods: GET

catch:
  path: /{any}
  controller: App\Controller\MainController::notFound
  requirements:
    any: ".*"